const dictionary = {
    inprogress: "진행중",
    accomcount: "수용인원",
    chkbabycarriage: "유모차대여 정보",
    chkcreditcard: "신용카드가능 정보",
    chkpet: "애완동물동반가능 정보",
    expagerange: "체험가능 연령",
    expguide: "체험안내",
    heritage1: "세계 문화유산 유무",
    heritage2: "세계 자연유산 유무",
    heritage3: "세계 기록유산 유무",
    infocenter: "문의 및 안내",
    opendate: "개장일",
    parking: "주차시설",
    restdate: "쉬는날",
    useseason: "이용시기",
    usetime: "이용시간",
    accomcountculture: "수용인원",
    chkbabycarriage: "유모차대여",
    culture: "정보",
    chkcreditcardculture: "신용카드가능 정보",
    chkpetculture: "애완동물동반가능 정보",
    discountinfo: "할인정보",
    infocenterculture: "문의 및 안내",
    parkingculture: "주차시설",
    parkingfee: "주차요금",
    restdateculture: "쉬는날",
    usefee: "이용요금",
    usetimeculture: "이용시간",
    scale: "규모",
    spendtime: "관람 소요시간",
    agelimit: "관람 가능연령",
    bookingplace: "예매처",
    discountinfofestival: "할인정보",
    eventenddate: "행사 종료일",
    eventhomepage: "행사 홈페이지",
    eventplace: "행사 장소",
    eventstartdate: "행사 시작일",
    festivalgrade: "축제등급",
    placeinfo: "행사장 위치안내",
    playtime: "공연시간",
    program: "행사 프로그램",
    spendtimefestival: "관람 소요시간",
    sponsor1: "주최자 정보",
    sponsor1tel: "주최자 연락처",
    sponsor2: "주관사 정보",
    sponsor2tel: "주관사 연락처",
    subevent: "부대행사",
    usetimefestival: "이용요금",
    distance: "코스 총거리",
    infocentertourcourse: "문의 및 안내",
    schedule: "코스 일정",
    taketime: "코스 총 소요시간",
    theme: "코스 테마",
    accomcountleports: "수용인원",
    chkbabycarriageleports: "유모차대여 정보",
    chkcreditcardleports: "신용카드가능 정보",
    chkpetleports: "애완동물동반가능 정보",
    expagerangeleports: "체험 가능연령",
    infocenterleports: "문의 및 안내",
    openperiod: "개장기간",
    parkingfeeleports: "주차요금",
    parkingleports: "주차시설",
    reservation: "예약안내",
    restdateleports: "쉬는날",
    scaleleports: "규모",
    usefeeleports: "입장료",
    usetimeleports: "이용시간",
    accomcountlodging: "수용 가능인원",
    benikia: "베니키아 여부",
    checkintime: "입실 시간",
    checkouttime: "퇴실 시간",
    chkcooking: "객실내 취사 여부",
    foodplace: "식음료장",
    goodstay: "굿스테이 여부",
    hanok: "한옥 여부",
    infocenterlodging: "문의 및 안내",
    parkinglodging: "주차시설",
    pickup: "픽업 서비스",
    roomcount: "객실수",
    reservationlodging: "예약안내",
    reservationurl: "예약안내 홈페이지",
    roomtype: "객실유형",
    scalelodging: "규모",
    subfacility: "부대시설 (기타)",
    barbecue: "바비큐장 여부",
    beauty: "뷰티시설 정보",
    beverage: "식음료장 여부",
    bicycle: "자전거 대여 여부",
    campfire: "캠프파이어 여부",
    fitness: "휘트니스 센터 여부",
    karaoke: "노래방 여부",
    publicbath: "공용 샤워실 여부",
    publicpc: "공용 PC실 여부",
    sauna: "사우나실 여부",
    seminar: "세미나실 여부",
    sports: "스포츠 시설 여부",
    refundregulation: "환불규정",
    chkbabycarriageshopping: "유모차대여 정보",
    chkcreditcardshopping: "신용카드가능 정보",
    chkpetshopping: "애완동물동반가능 정보",
    culturecenter: "문화센터 바로가기",
    fairday: "장서는 날",
    infocentershopping: "문의 및 안내",
    opendateshopping: "개장일",
    opentime: "영업시간",
    parkingshopping: "주차시설",
    restdateshopping: "쉬는날",
    restroom: "화장실 설명",
    saleitem: "판매 품목",
    saleitemcost: "판매 품목별 가격",
    scaleshopping: "규모",
    shopguide: "매장안내",
    chkcreditcardfood: "신용카드가능 정보",
    discountinfofood: "할인정보",
    firstmenu: "대표 메뉴",
    infocenterfood:	"문의 및 안내",
    kidsfacility: "어린이 놀이방 여부",
    opendatefood: "개업일",
    opentimefood: "영업시간",
    packing: "포장 가능",
    parkingfood: "주차시설",
    reservationfood: "예약안내",
    restdatefood: "쉬는날",
    scalefood: "규모",
    seat: "좌석수",
    smoking: "금연/흡연 여부",
    treatmenu: "취급 메뉴",
    lcnsno:	"인허가번호",
};

export default (en) => dictionary[en] ? dictionary[en] : '';